package ecom.entities;

// Generated Apr 3, 2018 11:08:32 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Product generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "product", catalog = "ecommerce")
public class Product implements java.io.Serializable {

	private Integer id;
	private Supplier supplier;
	private Category category;
	private Brand brand;
	private String code;
	private String name;
	private BigDecimal price;
	private String photo;
	private String description;
	private String chip;
	private String cpuSpeed;
	private String hardDrive;
	private String ram;
	private String graphics;
	private String resolution;
	private String lan;
	private String wifi;
	private String operatingSystem;
	private String pin;
	private Boolean fingerprintSensor;
	private Boolean keyboardLight;
	private String weight;
	private String warrantyPeriod;

	public Product() {
	}

	public Product(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public Product(Supplier supplier, Category category, Brand brand,
			String code, String name, BigDecimal price, String photo,
			String description, String chip, String cpuSpeed, String hardDrive,
			String ram, String graphics, String resolution, String lan,
			String wifi, String operatingSystem, String pin,
			Boolean fingerprintSensor, Boolean keyboardLight, String weight,
			String warrantyPeriod) {
		this.supplier = supplier;
		this.category = category;
		this.brand = brand;
		this.code = code;
		this.name = name;
		this.price = price;
		this.photo = photo;
		this.description = description;
		this.chip = chip;
		this.cpuSpeed = cpuSpeed;
		this.hardDrive = hardDrive;
		this.ram = ram;
		this.graphics = graphics;
		this.resolution = resolution;
		this.lan = lan;
		this.wifi = wifi;
		this.operatingSystem = operatingSystem;
		this.pin = pin;
		this.fingerprintSensor = fingerprintSensor;
		this.keyboardLight = keyboardLight;
		this.weight = weight;
		this.warrantyPeriod = warrantyPeriod;
	}
	public Product(Supplier supplier,
			String code, String name, BigDecimal price, String photo,
			String description, String chip, String cpuSpeed, String hardDrive,
			String ram, String graphics, String resolution, String lan,
			String wifi, String operatingSystem, String pin,
			Boolean fingerprintSensor, Boolean keyboardLight, String weight,
			String warrantyPeriod) {
		this.supplier = supplier;
		this.code = code;
		this.name = name;
		this.price = price;
		this.photo = photo;
		this.description = description;
		this.chip = chip;
		this.cpuSpeed = cpuSpeed;
		this.hardDrive = hardDrive;
		this.ram = ram;
		this.graphics = graphics;
		this.resolution = resolution;
		this.lan = lan;
		this.wifi = wifi;
		this.operatingSystem = operatingSystem;
		this.pin = pin;
		this.fingerprintSensor = fingerprintSensor;
		this.keyboardLight = keyboardLight;
		this.weight = weight;
		this.warrantyPeriod = warrantyPeriod;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplierId")
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryId")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brandId")
	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	@Column(name = "code", nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 10, scale = 0)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "photo", length = 250)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "chip", length = 100)
	public String getChip() {
		return this.chip;
	}

	public void setChip(String chip) {
		this.chip = chip;
	}

	@Column(name = "cpuSpeed", length = 100)
	public String getCpuSpeed() {
		return this.cpuSpeed;
	}

	public void setCpuSpeed(String cpuSpeed) {
		this.cpuSpeed = cpuSpeed;
	}

	@Column(name = "hardDrive", length = 100)
	public String getHardDrive() {
		return this.hardDrive;
	}

	public void setHardDrive(String hardDrive) {
		this.hardDrive = hardDrive;
	}

	@Column(name = "ram", length = 100)
	public String getRam() {
		return this.ram;
	}

	public void setRam(String ram) {
		this.ram = ram;
	}

	@Column(name = "graphics", length = 100)
	public String getGraphics() {
		return this.graphics;
	}

	public void setGraphics(String graphics) {
		this.graphics = graphics;
	}

	@Column(name = "resolution", length = 100)
	public String getResolution() {
		return this.resolution;
	}

	public void setResolution(String resolution) {
		this.resolution = resolution;
	}

	@Column(name = "lan", length = 100)
	public String getLan() {
		return this.lan;
	}

	public void setLan(String lan) {
		this.lan = lan;
	}

	@Column(name = "wifi", length = 100)
	public String getWifi() {
		return this.wifi;
	}

	public void setWifi(String wifi) {
		this.wifi = wifi;
	}

	@Column(name = "operatingSystem", length = 100)
	public String getOperatingSystem() {
		return this.operatingSystem;
	}

	public void setOperatingSystem(String operatingSystem) {
		this.operatingSystem = operatingSystem;
	}

	@Column(name = "pin", length = 100)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "fingerprintSensor")
	public Boolean getFingerprintSensor() {
		return this.fingerprintSensor;
	}

	public void setFingerprintSensor(Boolean fingerprintSensor) {
		this.fingerprintSensor = fingerprintSensor;
	}

	@Column(name = "keyboardLight")
	public Boolean getKeyboardLight() {
		return this.keyboardLight;
	}

	public void setKeyboardLight(Boolean keyboardLight) {
		this.keyboardLight = keyboardLight;
	}

	@Column(name = "weight", length = 100)
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "warrantyPeriod", length = 100)
	public String getWarrantyPeriod() {
		return this.warrantyPeriod;
	}

	public void setWarrantyPeriod(String warrantyPeriod) {
		this.warrantyPeriod = warrantyPeriod;
	}

}
