package ecom.entities;
// Generated May 13, 2018 9:45:54 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Supplier generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "supplier", catalog = "ecommerce")
public class Supplier implements java.io.Serializable {

	private Integer id;
	private String name;
	private String logo;
	private String linkHomePage;
	private String linkSearch;
	private String classListProduct;
	private String className;
	private String classPrice;
	private Set<Product> products = new HashSet<Product>(0);

	public Supplier() {
	}

	public Supplier(String name) {
		this.name = name;
	}

	public Supplier(String name, String logo, String linkHomePage, String linkSearch, String classListProduct,
			String className, String classPrice, Set<Product> products) {
		this.name = name;
		this.logo = logo;
		this.linkHomePage = linkHomePage;
		this.linkSearch = linkSearch;
		this.classListProduct = classListProduct;
		this.className = className;
		this.classPrice = classPrice;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "logo", length = 250)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "linkHomePage", length = 250)
	public String getLinkHomePage() {
		return this.linkHomePage;
	}

	public void setLinkHomePage(String linkHomePage) {
		this.linkHomePage = linkHomePage;
	}

	@Column(name = "linkSearch", length = 250)
	public String getLinkSearch() {
		return this.linkSearch;
	}

	public void setLinkSearch(String linkSearch) {
		this.linkSearch = linkSearch;
	}

	@Column(name = "classListProduct", length = 250)
	public String getClassListProduct() {
		return this.classListProduct;
	}

	public void setClassListProduct(String classListProduct) {
		this.classListProduct = classListProduct;
	}

	@Column(name = "className", length = 250)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "classPrice", length = 250)
	public String getClassPrice() {
		return this.classPrice;
	}

	public void setClassPrice(String classPrice) {
		this.classPrice = classPrice;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
